### ISSUE TITLE
Hour hand does not move linearly.

### ISSUE THREAD

**Issue by MoralCode** [DeveloperACE/MetricTime#5]
As expected with an analog clock, the hour hand should move to various degrees between each hour to indicate partial hours..

MetricTime doesn't:
![image](https://cloud.githubusercontent.com/assets/17362949/14752226/e912fdca-0882-11e6-933e-6b5e62baa188.png)
![image](https://cloud.githubusercontent.com/assets/17362949/14752227/e92fd954-0882-11e6-8196-e413666d92e8.png)

**Comment by DeveloperACE** [comment]
Fixed in commit 976905b602b0d384b1116d5b5a6ffb07a2f1e571
